Create DNF cache with -y before upgrading
QubesOS/qubes-mgmt-salt-dom0-update pull request #12
Opened 2020-12-18 19:39 UTC by DemiMarie

This is a prerequisite for https://github.com/QubesOS/qubes-core-agent-linux/pull/260

2020-12-18 20:09 UTC, marmarek requested changes

2020-12-18 20:09 UTC, marmarek commented on update/qubes-vm.sls
> +      - pkg: update
Running it always is intentional, see [commit which introduced it](https://github.com/QubesOS/qubes-mgmt-salt-dom0-update/commit/4ae92f868f9561422ceaba89ab42658a0d7cb285#diff-a809564b9a460228971ed88df7b64afe3d7c5070c1354c39bd4bb3b64a1fb702)

2020-12-18 20:09 UTC, marmarek commented on update/qubes-vm.sls
> +    - stateful: True
Just curious - why stateful (which requires this extra script)? Contrary to `dsa-4371-update`, it isn't critical to block the other call if makecache fails. Just more friendly status, or something else?

2020-12-18 21:00 UTC, DemiMarie commented on update/qubes-vm.sls
> +    - stateful: True
Mostly just for the friendly status.  I got tired of seeing “changed = 2” when nothing had actually changed.

2020-12-18 21:00 UTC, DemiMarie commented on update/qubes-vm.sls
> +      - pkg: update
Good point.  I’ll revert this, and make it stateful in a future PR.

2020-12-22 20:25 UTC, DemiMarie commented
That OpenQA failure looks to be because a package isn’t signed correctly.  What could cause that?

2020-12-22 22:12 UTC, marmarek commented
No, it was missing `dnf -y makecache` after enabling metadata check. The test run with updated `upgrades-installed-check` (that passes `-y` to `dnf check-update`) is still running. Earlier runs with that change failed because of bug in https://github.com/QubesOS/qubes-core-agent-linux/pull/269, which I now excluded from the run.

2020-12-28 15:39 UTC, merged